name: Detect Changes
on:
  workflow_call:
    outputs:
      aws:
        value: ${{ jobs.changes.outputs.aws }}
      apis:
        value: ${{ jobs.changes.outputs.apis }}
      wiki:
        value: ${{ jobs.changes.output.wiki }}
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      aws: ${{ steps.filter.outputs.aws }}
      apis: ${{ steps.filter.outputs.apis }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            apis:
              - 'apis/**'
            aws:
              - 'aws/**'
