name: Deploy-Beta
run-name: Deploy to Beta by @${{ github.actor }}
on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test-apis:
    uses: ./.github/workflows/test.yml

  deploy-beta:
    name: Deploy to beta
    needs:
      - test-apis

    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: beta
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
