name: Deploy-prod
run-name: Deploy to Production by @${{ github.actor }}
on:
  workflow_dispatch:
    branches: [main]
  release:
    types: [published]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-prod:
    name: Deploy to production
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: prod
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
