name: Run tests
on:
  workflow_call:
    inputs:
      root-directory:
        type: string
        required: false
        default: "./"
        
jobs:
  run-node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: aws/yarn.lock
          node-version: "16.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile
        working-directory: ${{ inputs.root-directory }}

      - run: yarn test
        name: Test node project
        working-directory: ${{ inputs.root-directory }}
