name: Install Node dependencies
on:
  workflow_call:
    secrets:
      github-token:
        required: true
        type: string
jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: aws/yarn.lock
          node-version: "16.x"
          cache: "yarn"
      - run: |
          CAT <<EOF > .npmrc
          registry=https://registry.yarnpkg.com/

          @nanaduah1:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.github-token }}
          always-auth=true
          EOF
        working-directory: aws

      - run: yarn install --frozen-lockfile && yarn test
        name: Test aws
        working-directory: aws

  