name: Run Linters
on:
  workflow_call:
    inputs:
      root-directory:
        type: string
        required: false
        default: "."
      
      node_version:
        type: string
        required:  false
        default: "18.x"
        
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: aws/yarn.lock
          node-version: ${{ inputs.node_version }}
          cache: "yarn"
        
      - run: |
          ROOT_DIR=$(pwd)
          find ${{ inputs.root-directory }} -name package.json -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && yarn install && yarn lint; done
      
