name: Run tests
on:
  workflow_call:
    inputs:
      root-directory:
        type: string
        required: false
        default: "./src"

      dynamodb:
        type: string
        required: false
        default: off

      node_version:
        type: string
        required: false
        default: "18.x"

      python_version:
        type: string
        required: false
        default: "3.9"

      poetry_version:
        type: string
        required: false
        default: "1.3.2"

jobs:
  run-node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: aws/yarn.lock
          node-version: ${{ inputs.node_version }}
          cache: "yarn"

      - run: yarn install --frozen-lockfile
        working-directory: aws

      - run: yarn test
        name: Test aws
        working-directory: aws

  run-python-tests:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_DYNAMODB_ENDPOINT: http://localhost:8000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Setup DynamoDB Local
        if: inputs.dynamodb == 'on'
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: "*"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ inputs.poetry_version }}

      - run: |
          ROOT_DIR=$(pwd)
          find ${{ inputs.root-directory }} -name pyproject.toml -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && poetry install; done

      - run: |
          ROOT_DIR=$(pwd)
          find ${{ inputs.root-directory }} -name pyproject.toml -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && poetry run pytest -rP; done
