name: Run tests
on:
  workflow_call:
    inputs:
      root-directory:
        type: string
        required: false
        default: "./src"

      dynamodb:
        type: string
        required: false
        default: off
        
jobs:
  run-node-tests:
    permissions:
      actions: write
      checks: write
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: aws/yarn.lock
          node-version: "20.x"
          cache: "yarn"
          registry-url: "@nanaduah1:registry=https://npm.pkg.github.com"

      - run: yarn install --frozen-lockfile
        working-directory: aws

      - run: yarn test
        name: Test aws
        working-directory: aws

  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup DynamoDB Local
        if: inputs.dynamodb == 'on'
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: "*"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"

      - run: |
          ROOT_DIR=$(pwd)
          find ${{ inputs.root-directory }} -name pyproject.toml -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && poetry install; done

      - run: |
          ROOT_DIR=$(pwd)
          find ${{ inputs.root-directory }} -name pyproject.toml -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && poetry run pytest -rP; done
      
      
