name: Run tests
on:
  workflow_call:
    secrets:
      github-token:
        required: true
        
jobs:
  run-node-tests:
    permissions:
      actions: write
      checks: write
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: aws/yarn.lock
          node-version: "16.x"
          cache: "yarn"
          registry-url: "@nanaduah1:registry=https://npm.pkg.github.com"

      - run: yarn install --frozen-lockfile
        working-directory: aws

      - run: yarn test
        name: Test aws
        working-directory: aws

  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - run: |
          ROOT_DIR=$(pwd)
          find ./src -name pyproject.toml -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && poetry install; done
      - run: pip3 install pytest
      - run: pytest
