name: Run tests
on:
  workflow_call:
    secrets:
      github-token:
        required: true
        
jobs:
  run-node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./github/workflows/node-install
        with:
          github-token: ${{ secrets.github-token }}

      - run: yarn install --frozen-lockfile && yarn test
        name: Test aws
        working-directory: aws

  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - run: |
          ROOT_DIR=$(pwd)
          find ./src -name pyproject.toml -printf "%h\n" | sort -nr | while read -r i; do cd $ROOT_DIR && cd "$i" && poetry install; done
      - run: pip3 install pytest
      - run: pytest
